/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import Model.Encounter;
import Model.Patient;
import Model.PatientDirectory;
import Model.VitalSigns;
import javax.swing.JOptionPane;

/**
 *
 * @author ajay09
 */
public class BPAbnormalityJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BPAbnormalityJPanel
     */
    PatientDirectory patients;
    Encounter encounter;
    VitalSigns vitalSigns;
    
    public BPAbnormalityJPanel(PatientDirectory patients, Encounter encounter, VitalSigns vitalSigns) {
        initComponents();
        this.patients = patients;
        this.encounter = encounter;
        this.vitalSigns = vitalSigns;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatient = new javax.swing.JTable();
        btnCommunity2 = new javax.swing.JButton();
        btnCommunity1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Patients With Abnormal Blood Pressure");

        tblPatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient Name", "Patient ID", "Age", "House", "Community", "City", "BP", "Temperature", "Pulse"
            }
        ));
        jScrollPane1.setViewportView(tblPatient);

        btnCommunity2.setText("Community 2");
        btnCommunity2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommunity2ActionPerformed(evt);
            }
        });

        btnCommunity1.setText("Community 1");
        btnCommunity1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommunity1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCommunity1)
                .addGap(34, 34, 34)
                .addComponent(btnCommunity2)
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCommunity2)
                    .addComponent(btnCommunity1))
                .addContainerGap(212, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCommunity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommunity1ActionPerformed
        // TODO add your handling code here:
        try{
            
        String name = txtName.getText();
        String patientID = (txtPatientID.getText());
        String houseNumber = txtHouse.getText();
        String cityName = txtCity.getText();
        String communityName = txtCommunity.getText();
        int age = Integer.parseInt(txtAge.getText());
        double pulseRate = Double.parseDouble(txtPulseRate.getText());
        double bodyTemperature = Double.parseDouble(txtBodyTemperature.getText());
        double bloodPressure = Double.parseDouble(txtBloodPressure.getText());
        
        Patient patient = patients.addNewPatient();
        
        patient.setName(name);
        patient.setPatientID(patientID);
        patient.setAge(age);
        patient.setHouseNumber(houseNumber);
        patient.setCityName(cityName);
        patient.setCommunityName(communityName);
        vitalSigns.setPulseRate(pulseRate);
        vitalSigns.setBodyTemperature(bodyTemperature);
        vitalSigns.setBloodPressure(bloodPressure);
        } catch(Exception e){}
        
        JOptionPane.showMessageDialog(this, "Patient Details Added Successfully.");
        
        txtName.setText("");
        txtPatientID.setText("");
        txtAge.setText("");
        txtHouse.setText("");
        txtCommunity.setText("");
        txtCity.setText("");
        txtPulseRate.setText("");
        txtBodyTemperature.setText("");
        txtBloodPressure.setText("");
    }                     
    }//GEN-LAST:event_btnCommunity1ActionPerformed

    private void btnCommunity2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommunity2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCommunity2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCommunity1;
    private javax.swing.JButton btnCommunity2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPatient;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
