/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import Model.Encounter;
import Model.Patient;
import Model.PatientDirectory;
import Model.VitalSigns;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ajay09
 */
public class ViewPatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form viewPanel
     */
    PatientDirectory listOfPatients;
    Encounter encounter;
    VitalSigns vitalSigns;
    
    public ViewPatientJPanel(PatientDirectory listOfPatients, Encounter encounter, VitalSigns vitalSigns) {
        initComponents();
        this.listOfPatients = listOfPatients;
        this.encounter = encounter;
        this.vitalSigns = vitalSigns;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatient = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblPatientNameView = new javax.swing.JLabel();
        lblPatientIDView = new javax.swing.JLabel();
        lblAgeView = new javax.swing.JLabel();
        lblHouseView = new javax.swing.JLabel();
        lblCommunityView = new javax.swing.JLabel();
        lblCityView = new javax.swing.JLabel();
        txtPatientNameView = new javax.swing.JTextField();
        txtAgeView = new javax.swing.JTextField();
        txtPatientIDView = new javax.swing.JTextField();
        txtHouseView = new javax.swing.JTextField();
        txtCommunityView = new javax.swing.JTextField();
        txtCityView = new javax.swing.JTextField();
        btnUpdateV = new javax.swing.JButton();
        lblBPView = new javax.swing.JLabel();
        txtBPView = new javax.swing.JTextField();
        lblTempView = new javax.swing.JLabel();
        txtTempView = new javax.swing.JTextField();
        lblPulseView = new javax.swing.JLabel();
        txtPulseView = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Patient");

        tblPatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient Name", "Patient ID", "Age", "House", "Community", "City", "BP", "Temperature", "Pulse"
            }
        ));
        jScrollPane1.setViewportView(tblPatient);

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblPatientNameView.setText("Patient Name");

        lblPatientIDView.setText("Patient ID");

        lblAgeView.setText("Age");

        lblHouseView.setText("House");

        lblCommunityView.setText("Community");

        lblCityView.setText("City");

        txtAgeView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeViewActionPerformed(evt);
            }
        });

        txtPatientIDView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientIDViewActionPerformed(evt);
            }
        });

        txtCityView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityViewActionPerformed(evt);
            }
        });

        btnUpdateV.setText("Update");
        btnUpdateV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateVActionPerformed(evt);
            }
        });

        lblBPView.setText("Blood Pressure");

        lblTempView.setText("Body Temperature");

        txtTempView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTempViewActionPerformed(evt);
            }
        });

        lblPulseView.setText("Pulse Rate");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 172, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnUpdateV)
                                .addGap(329, 329, 329))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblPatientIDView)
                                        .addComponent(lblPatientNameView)
                                        .addComponent(lblAgeView))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblHouseView)
                                            .addComponent(lblCommunityView)
                                            .addComponent(lblCityView))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHouseView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCommunityView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCityView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnView)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnDelete))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtAgeView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtPatientIDView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtPatientNameView, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(31, 31, 31)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblTempView)
                                                .addComponent(lblBPView)
                                                .addComponent(lblPulseView))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtPulseView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtTempView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtBPView, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(142, 142, 142))))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAgeView, txtCityView, txtCommunityView, txtHouseView, txtPatientIDView, txtPatientNameView});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBPView, txtPulseView, txtTempView});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnView))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatientNameView)
                            .addComponent(txtPatientNameView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatientIDView)
                            .addComponent(txtPatientIDView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAgeView)
                            .addComponent(txtAgeView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBPView)
                            .addComponent(txtBPView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTempView)
                            .addComponent(txtTempView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPulseView)
                            .addComponent(txtPulseView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHouseView)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtHouseView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCommunityView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCommunityView))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCityView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCityView))))
                .addGap(18, 18, 18)
                .addComponent(btnUpdateV)
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPatientIDViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientIDViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientIDViewActionPerformed

    private void txtCityViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityViewActionPerformed

    private void txtTempViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTempViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTempViewActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
       int selectedRowIndex = tblPatient.getSelectedRow();
       

        DefaultTableModel model = (DefaultTableModel) tblPatient.getModel();
        Patient selectedPatientDetails = (Patient)model.getValueAt(selectedRowIndex, 0);
        
        VitalSigns selectedVitalSign = (VitalSigns)model.getValueAt(selectedRowIndex, 1);
        
        txtPatientNameView.setText(selectedPatientDetails.getName());
        txtPatientIDView.setText(selectedPatientDetails.getPatientID());
        txtAgeView.setText(String.valueOf(selectedPatientDetails.getAge()));
        txtHouseView.setText(selectedPatientDetails.getHouseNumber());
        txtCommunityView.setText(selectedPatientDetails.getCommunityName());
        txtCityView.setText(selectedPatientDetails.getCityName());
        
        txtBPView.setText(String.valueOf(selectedVitalSign.getBloodPressure()));
        txtTempView.setText(String.valueOf(selectedVitalSign.getBodyTemperature()));
        txtPulseView.setText(String.valueOf(selectedVitalSign.getPulseRate()));
        
    }//GEN-LAST:event_btnViewActionPerformed

    private void txtAgeViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblPatient.getSelectedRow();

        if(selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Patient Detail to Delete !!!");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblPatient.getModel();
        Patient selectedPatient = (Patient)model.getValueAt(selectedRowIndex, 0);
        
        listOfPatients.deletePatient(selectedPatient);
        JOptionPane.showMessageDialog(this, "Patient Detail Deleted !!!");
        
        populateTable();
        txtPatientNameView.setText("");
        txtPatientIDView.setText("");
        txtAgeView.setText("");
        
        txtHouseView.setText("");
        
        txtCommunityView.setText("");
        txtCityView.setText("");
        
        
        txtBPView.setText("");
        txtTempView.setText("");
        
        txtPulseView.setText("");
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateVActionPerformed
        // TODO add your handling code here:
        int i = tblPatient.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)tblPatient.getModel();
        Patient selectedPatient = (Patient)model.getValueAt(i, 0);
        VitalSigns selectedVitalSign = (VitalSigns)model.getValueAt(i, 0);
        
        selectedPatient.setName(txtPatientNameView.getText());
        selectedPatient.setPatientID(txtPatientIDView.getText());
        selectedPatient.setAge(Integer.parseInt(txtAgeView.getText()));
        
        selectedPatient.setHouseNumber(txtHouseView.getText());
        selectedPatient.setCommunityName(txtCommunityView.getText());
        selectedPatient.setCityName(txtCityView.getText());
        selectedVitalSign.setBloodPressure(Double.parseDouble(txtBPView.getText()));
        selectedVitalSign.setBodyTemperature(Double.parseDouble(txtTempView.getText()));
        selectedVitalSign.setPulseRate(Double.parseDouble(txtPulseView.getText()));
                 
        listOfPatients.updatePatientList(i, selectedPatient);
        JOptionPane.showMessageDialog(this, "Vitals Added Successfully !!!");
        if(i >= 0) {
            model.setValueAt(txtPatientNameView.getText(), i, 0);
            model.setValueAt(txtPatientIDView.getText(), i, 1);
            model.setValueAt(txtAgeView.getText(), i, 2);
            model.setValueAt(txtHouseView.getText(), i, 3);
            
            model.setValueAt(txtCommunityView.getText(), i, 4);
            model.setValueAt(txtCityView.getText(), i, 5);
            model.setValueAt(txtBPView.getText(), i, 6);
            model.setValueAt(txtTempView.getText(), i, 7);
            model.setValueAt(txtPulseView.getText(), i, 8);
            
        }
        else {
            JOptionPane.showMessageDialog(this, "Error Updating Field !!!");
        }
        populateTable();
        txtPatientNameView.setText("");
        txtPatientIDView.setText("");
        txtAgeView.setText("");
        
        txtHouseView.setText("");
        
        txtCommunityView.setText("");
        txtCityView.setText("");
        
        txtBPView.setText("");
        txtTempView.setText("");
        
        txtPulseView.setText("");
    }//GEN-LAST:event_btnUpdateVActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdateV;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAgeView;
    private javax.swing.JLabel lblBPView;
    private javax.swing.JLabel lblCityView;
    private javax.swing.JLabel lblCommunityView;
    private javax.swing.JLabel lblHouseView;
    private javax.swing.JLabel lblPatientIDView;
    private javax.swing.JLabel lblPatientNameView;
    private javax.swing.JLabel lblPulseView;
    private javax.swing.JLabel lblTempView;
    private javax.swing.JTable tblPatient;
    private javax.swing.JTextField txtAgeView;
    private javax.swing.JTextField txtBPView;
    private javax.swing.JTextField txtCityView;
    private javax.swing.JTextField txtCommunityView;
    private javax.swing.JTextField txtHouseView;
    private javax.swing.JTextField txtPatientIDView;
    private javax.swing.JTextField txtPatientNameView;
    private javax.swing.JTextField txtPulseView;
    private javax.swing.JTextField txtTempView;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        DefaultTableModel model = (DefaultTableModel) tblPatient.getModel();
        model.setRowCount(0);
        for(Patient patient : listOfPatients.getListOfPatients()){
            Object[] row = new Object[9];
            
            row[0] = patient.getName();
            row[1] = patient.getPatientID();
            row[2] = patient.getAge();
            row[3] = patient.getHouseNumber();
            row[4] = patient.getCommunityName();
            row[5] = patient.getCityName();
            row[6] = vitalSigns.getBloodPressure();
            row[7] = vitalSigns.getBodyTemperature();
            row[8] = vitalSigns.getPulseRate();
            
            model.addRow(row);
        }
        
        
    }
}
